### ISSUE TITLE
Doc job is failing

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/robotiq#10]
The robotiq document job is failing, see [here](http://jenkins.ros.org/job/doc-indigo-robotiq/4/console).  The problem appears to be due to a faulty `catkin_package` delcaration, see [here](https://github.com/ros-industrial/robotiq/blob/groovy-devel/robotiq_modbus_rtu/CMakeLists.txt#L22).

`python-pymodbus` is not a catkin package.  It should probably moved under a regular `DEPENDS`.  This might fix the doc job.  I'm not sure if `python-pymodbus` is a standard library, so it may still cause issues.

**Comment by shaun-edwards** [comment]
@mikepurvis, this is currently preventing the wiki from updating.

**Comment by nicolaslauzier** [comment]
I'm not very familiar with Depends in ROS but pymodbus can be installed using "apt-get install python-pymodbus". 

Where can we define it as a regular depends?

**Comment by gavanderhoorn** [comment]
On 3-12-2014 20:17, nicolaslauzier wrote:

> I'm not very familiar with Depends in ROS but pymodbus can be installed using "apt-get install python-pymodbus". 
> 
> Where can we define it as a regular depends?

Only catkin packages should be listed after `CATKIN_DEPENDS`. Any
non-catkin package should just be declared using `DEPENDS`. Just add it to the `catkin_package(..)` statement.

Edit: as @shaun-edwards already wrote .. sorry for the noise.

**Comment by mikepurvis** [comment]
I actually don't have write access to https://github.com/ros-industrial/robotiq/ or anything else in ROS-I. @shaun-edwards, can you take care of making the necessary change?

**Comment by shaun-edwards** [comment]
@mikepurvis, I mentioned you so that you knew why the wiki wasn't updating (I believe you were the one that submitted the `rosdistro` update.

@nicolaslauzier, can you make the change?  What @gavanderhoorn  suggests should work.

**Comment by mikepurvis** [comment]
Okay, yes, thanks. My apologies for not keeping closer tabs on this.

**Comment by nicolaslauzier** [comment]
@shaun-edwards, I did make/commit the changes for both branches (I still haven't created an Indigo branch yet, sorry about this).  Should we wait for Jenkins to run again or is there a way to tell it to do a new pass?

@gavanderhoorn and @shaun-edwards, thanks for the help!

**Comment by shaun-edwards** [comment]
@nicolaslauzier, I went ahead and created the indigo branch (it's easy to do from the web).  I believe we will have to wait until next week for jenkins to run a new pass.

**Comment by nicolaslauzier** [comment]
@shaun-edwards, thanks! I've been away from ROS and github for a while now and it seems that I forgot how easy it can be! =o)

**Comment by gavanderhoorn** [comment]
I just remembered that python-only dependencies do not get added to the `DEPENDS` list of the `catkin_package(..)` statement. From [Python module dependencies](http://docs.ros.org/indigo/api/catkin/html/howto/format1/python_module_dependencies.html):

> Your `CMakeLists.txt` need not specify Python-only dependencies. They are resolved automatically via sys.path.

They should just be listed as `run_depend`s and `build_depend`s in the package manifest.

**Comment by shaun-edwards** [comment]
Still broken :( ([here](http://jenkins.ros.org/job/doc-indigo-robotiq/5/console)).  Looks like @gavanderhoorn may be right.  Sorry I can't provide much guidance on this one.  I'm not that familiar with python/catkin.  @nicolaslauzier, can you try what @gavanderhoorn suggests?

**Comment by dirk-thomas** [comment]
I just run into the same problem on the new build farm. The problem is the `requires` entry in the `setup.py` file of the `robotiq_modbus_rtu` package: https://github.com/ros-industrial/robotiq/blob/0fc9203ff93a39880446234bcf1dfd7eaff00a0b/robotiq_modbus_rtu/setup.py#L10
Basically the part after the dash in `python-pymodbus` is being interpreted as a versioned dependency - but it doesn't parse as a version number.

I guess removing that line is the correct solution.

**Comment by gavanderhoorn** [comment]
@dirk-thomas: removing the `python-` prefix should also work (see #22)?

**Comment by dirk-thomas** [comment]
I am not sure why to keep the `require` entry since the setup.py file of catkin packages is commonly not supposed to be invoked directly.

But yes, I assume removing the prefix should make it work.

**Comment by gavanderhoorn** [comment]
Seems like all doc jobs have run to completion now. Version rocker on the wiki pages is missing only the `groovy` button, but since the groovy buildfarm is gone, the doc jobs aren't run anymore for that distro.

**Comment by nicolaslauzier** [comment]
Thanks for that!

2015-05-27 2:57 GMT-04:00 G.A. vd. Hoorn notifications@github.com:

> Seems like all doc jobs have run to completion now. Version rocker on the
> wiki pages is missing only the groovy button, but since the groovy
> buildfarm is gone, the doc jobs aren't run anymore for that distro.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/robotiq/issues/10#issuecomment-105782539
> .

## 

_Nicolas Lauzier, ing., *_Eng., Ph. D.*
_Chargé de projet / Project Manager_
1-888-ROBOTIQ (762-6847) ext. 206

nicolas@robotiq.com
robotiq.com
blog.robotiq.com

Follow us on / Suivez-nous sur
http://www.facebook.com/pages/Robotiq/122478611152517
https://plus.google.com/u/0/b/100363269019698451101/100363269019698451101/posts

http://www.linkedin.com/company/1695451?goback=%2Efcs_GLHD_robotiq_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits
  https://twitter.com/?lang=en&logged_out=1#%21/SamBouchard
http://www.youtube.com/user/RobotiqTV
