### ISSUE TITLE
lose calibration each time the robot starts

### ISSUE THREAD

**Issue by ghost** [ros-industrial-attic/robotiq#106]
Hey all,

I have a robotiq FT300 and I'm using Ubuntu 14.04 with ROS Indigo. I used the calibration procedure in the manual, load the program in polyscope and calibrate the sensor. After the calibration, everything works fine. But whenever I restart my computer or the robot, I would lose this calibration. Fz can be 10 or 5 or 3(drift) even when there is no force input.

I powered the FT300 from the UR control box(CB3), and connection is through the USB connector provided by Robotiq to my computer. I wonder if you guys can help me out.

Thank you in advance.

best,

**Comment by shaun-edwards** [comment]
@nicolaslauzier

**Comment by nicolaslauzier** [comment]
Hi,

@Thompson104 Please contact Robotiq support at support@robotiq.com for help with our products.

Best regards,

**Comment by ghost** [comment]
@shaun-edwards @nicolaslauzier 
Thank you for your attention. I just sent the email and hopefully we can get this solved. My defense is only 1 month from now lol.
