### ISSUE TITLE
 More than 80% of the sampled goal states fail to satisfy the constraints imposed on the goal sampler. Is the constrained sampler working correctly?

### ISSUE THREAD

**Issue by xs-alt** [ros-industrial-attic/robotiq#125]
Hi all, l am just working on the robotiq-140 gripper with UR10 robot arm under ROS Kinectic.
![joint](https://user-images.githubusercontent.com/24916161/38763848-dbf970be-3fd6-11e8-9fd7-51c12a900ddc.png)
l use moveit_setup_assistant to config the package. And run the demo.launch, l would like to see if l can plan the gripper in Moveit. l update the gripper to random goal state and click the plan button , and some errors happen like the following. 
![2018-04-14 11-30-28](https://user-images.githubusercontent.com/24916161/38763871-45f37776-3fd7-11e8-974a-85ddce4a8d58.png)
After that l write some code to plan the gripper, and error happens,
![2018-04-14 11-33-02](https://user-images.githubusercontent.com/24916161/38763883-9f1cc2d0-3fd7-11e8-8861-a58fae9dbf0e.png)
![2018-04-14 11-34-31](https://user-images.githubusercontent.com/24916161/38763892-d5dbdf04-3fd7-11e8-80f3-36e2bfd4b905.png)
so l am confused about it and really do not know how to deal with the problem.
can anyone helps me? Thank you.

**Comment by xs-alt** [comment]
Actually, l try a lot of methods to solve this problem.
First, about the Constraint violated: l change the plan group(gripper) to only contain the finger joint, then l could plan the gripper in Moveit Rviz.
Second l was told that the plan cannot simply be executed because of lacking controllers. See [here ](https://github.com/beta-robots/robotiq/issues/7)

**Comment by jatinagarwal1308** [comment]
I am using ur5 2 finger gripper controller and getting the same error in python 
@bringBackm can you please guide me how to get rid of it?
Thanks in advance

**Comment by xs-alt** [comment]
@jatinagarwal1308  
It seems to be the wrong configuration.

**Comment by shipeiZ** [comment]
Limits are wrong. Change lower limits opposite to upper limits for all joints except finger joint
take  inner_knuckle_joint as example
origin :<limit lower="0" upper="0.8757" velocity="2.0" effort="1000" />
modified :<limit lower="-0.8757" upper="0.8757" velocity="2.0" effort="1000" />
