### ISSUE TITLE
Ported to ROS 2.0

### ISSUE THREAD

**Issue by RoboticsYY** [ros-industrial-attic/robotiq#144]
Is there a plan or an estimated date to port this package to ROS 2.0?

Thanks!

**Comment by nicolaslauzier** [comment]
Hi!

Acutronics made ROS 2.0 packages for the 2F and Hand-E grippers: https://github.com/AcutronicRobotics/robotiq_modular_gripper

Hope this helps!

**Comment by RoboticsYY** [comment]
@nicolaslauzier Great news! I will try that. Thanks!
