### ISSUE TITLE
Robotiq_3f_gripper shakes with the ur10 robot

### ISSUE THREAD

**Issue by padhupradheep** [ros-industrial-attic/robotiq#147]
Hey guys, 

I'm using ur10 robot and trying to connect Robotiq 3f gripper. The problem is that the gripper vibrates/shakes too much in the gazebo simulation.  I tried adding kp, kd, mu1 and mu2 parameters but still the robot is shaking.  What should I be doing?

**Comment by jproberge** [comment]
Hi,

I have the exact same problem as the one you are describing with the 2f gripper. I'm still trying to find a solution about that, I'll write back as soon as I find one. Just to be clear though, is it the robot or the gripper that's vibrating in your case?

**Comment by padhupradheep** [comment]
Hey,

Thanks for the response ! 

In my case, gripper is vibrating.

**Comment by pidipidi** [comment]
I also faced the same issue when I use a UR5. There were two reasons. One is the strict position control of UR5/10 generates vibration in Gazebo. If you use the joint effort control in simulation, you can suppress the physics issue. Another one is there can be self-collision between your gripper and UR10. If you disable it, you can reduce the vibration. You can just disable it in ur.gazebo.xacro.

**Comment by jproberge** [comment]
@pidipidi this indeed solved the issue on our side! Thanks for your comment!
