### ISSUE TITLE
ROS2-devel

### ISSUE THREAD

**Issue by YongLD** [ros-industrial-attic/robotiq#194]
##### QUESTION
Will this update the ROS2-devel?
I realize that this repository is unmaintained, but we do need the ROS2-supported.

**Comment by gavanderhoorn** [comment]
To reiterate: this repository does indeed seem unmaintained.

I would not expect a ROS 2 port / ROS 2 related development to happen / be coordinated in this repository.

**Comment by YongLD** [comment]
@gavanderhoorn  Thanks for reply. Is there any robotiq driver can I utilize if I want to use the robotiq gripper in ROS2?

**Comment by gavanderhoorn** [comment]
I would not know I'm afraid.

We don't maintain this, the repository is only hosted here for historical reasons.

**Comment by YongLD** [comment]
@gavanderhoorn Anyway, thank you very much!
