### ISSUE TITLE
rosdep install robotiq_modbus_tcp failed 

### ISSUE THREAD

**Issue by zhengnx0906** [ros-industrial-attic/robotiq#198]
> Rosdep can't find a reference in their config file ([should be this one](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml)) for `python-pymodbus` so it tries to call it directly, which fails.
> 
> You could try `apt-get install python3-pymodbus` or follow the instructions: [pymodbus](https://pymodbus.readthedocs.io/en/latest/readme.html#installing). But there could be more issues with noetic on this old repo.

Thanks for your suggestion. It works.

_Originally posted by @MZJR in https://github.com/ros-industrial/robotiq/issues/195#issuecomment-983222228_
sry, I successfully install python3-pymodbus, but 'rosdep install robotiq_modbus_tcp' is still faild to execute. Is anything else i need to do?

**Comment by JohnnyMudcrab** [comment]
Have you also changed the dependency inside the package.xml from `python-pymodbus` to `python3-pymodbus`?

**Comment by zhengnx0906** [comment]
Thank you, it works.
