### ISSUE TITLE
tcp and rtu modules cause catkin_make install to fail

### ISSUE THREAD

**Issue by mdedonato** [ros-industrial-attic/robotiq#22]
It should be a simple fix, but catkin_make install fails on these two packages.

**Comment by gavanderhoorn** [comment]
The cause of the failure seems to be the same as reported by @dirk-thomas in #10: the `requires` field in `setup.py`.

Removing the field 'solves' the issue with `catkin_make install` (and most likely also the doc job problem). However, I assume the `requires` field was put in for a reason (namely: to express a dependency on the listed modules). For ROS at least, that dependency is already expressed in the package manifest using the `run_depend` and `build_depend` elements.

If we want to keep this, and [pypi/pymodbus](https://pypi.python.org/pypi/pymodbus) is what the `python-pymodbus` entry in `requires` is refering to, then simply removing the `python-` prefix also seems to work (I'm guessing the package is called `python-pymodbus` on Ubuntu).
