### ISSUE TITLE
Request for release: Indigo

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-industrial-attic/robotiq#23]
If this could be released into Indigo that'd be great!

**Comment by shaun-edwards** [comment]
Robotiq has never been released (as a deb).  The primary hurdle has been what to do with the [pymodbus](http://wiki.ros.org/robotiq/Tutorials/Control%20of%20an%20S-Model%20Gripper%20using%20the%20Modbus%20TCP%20Protocol#Prerequisites) dependency.  I haven't had time to look into it.  Pymodbus is not available via apt-get.

**Comment by UltronDestroyer** [comment]
Hmmm, I wonder if we can get around that..
