### ISSUE TITLE
Wiki page doesn't show groovy version

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/robotiq#3]
The [robotiq](http://wiki.ros.org/robotiq) wiki page does not show the repo location for the groovy release.  This information should be added to the appropriate rosdistro file.  The groovy version is hosted on google code [here](https://code.google.com/p/swri-ros-pkg/source/browse/#svn%2Fbranches%2Fgroovy%2Frobotiq)

**Comment by mikepurvis** [comment]
Groovy is EOL and the buildfarm jobs have been stopped, so this ship has sailed. However, I've filed a PR to add indexing for Hydro and Indigo:

https://github.com/ros/rosdistro/pull/6325
