### ISSUE TITLE
EtherCAT robotiq packages require external library

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/robotiq#38]
The EtherCAT packages require a forked version of [SOEM](https://github.com/ros-industrial/ethercat-soem).  This is not documented anywhere and could potentially trip up some users.

A _Installation from Source_ section should be added to the [wiki page](http://wiki.ros.org/robotiq).  Current dependencies are:
- SOEM
- pyModbus - From tutorial `Finally, make sure that the external dependency for the package "robotiq_modbus_tcp" has been installed. The dependency is the python package pyModbus. On Ubuntu Precise, it is simply installed using "rosdep install robotiq_modbus_tcp". On other systems, it can be installed using "easy_install -U pymodbus"`

**Comment by shaun-edwards** [comment]
@Jmeyer1292, I haven't verified this issue, but I believe we need to add these instructions to assist the users in installing dependencies.  This should be a quick change.

**Comment by gavanderhoorn** [comment]
Please avoid using `easy_install` (from `setuptools`), use `pip`. But then only if really necessary, as it circumvents your system's package manager.

**Comment by Jmeyer1292** [comment]
I'll get on it.

**Comment by shaun-edwards** [comment]
I added installation instructions to the [wiki](http://wiki.ros.org/robotiq#Installation).  This is just a temporary fix until #39 is addressed.

**Comment by theNerd247** [comment]
The documentation on the wiki is a bit misleading. It requests the package [here](https://github.com/ros-industrial/ethercat-soem) to be installed in the catkin workspace however, robotiq_ethercat requires  the soem package...it's causing a bunch of catkin_make errors. Namely, the soem package can't be  found. According to #39 I'm assuming we should go for the debian package instead? Or at least that's what the robotiq_ethercat package is assuming (based on  032d4c47). If this is the case please update the wiki.

**Comment by Jmeyer1292** [comment]
Yes, I believe since the change you should use the debian package for soem that can be obtained by `sudo apt-get install ros-indigo-soem`.

@theNerd247 Can you please point out to me where the incorrect information is? Thanks.

**Comment by theNerd247** [comment]
On [this](http://wiki.ros.org/robotiq) page. The section that says to clone this repo: 

```
git clone https://github.com/ros-industrial/ethercat-soem.git
```

I believe

```
sudo apt-get install ros-indigo-soem
```

Is what you mean now - or at least that's what worked for me.

**Comment by shaun-edwards** [comment]
@theNerd247, my apologies.  I fixed the original issue, but failed to update the documentation.  I've update the wiki with the apt-get installation.  Thanks for pointing this out!
