### ISSUE TITLE
Utilize soem ROS package instead of forked ethercat_soem

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/robotiq#39]
A ROS SOEM library already exists as a debian in Indigo (it's built from [here](https://github.com/smits/soem)).  The latest merges to support an EtherCAT version of the robotiq gripper require a forked version, [here](https://github.com/ros-industrial/ethercat-soem).  

I believe the original version was forked to provide catkin support.  This now exists in the original SOEM version.  If we utilized the existing ROS debian version of SOEM, we could do official debian releases of the robotiq packages.

**Comment by shaun-edwards** [comment]
@Jmeyer1292, can you comment?

**Comment by Jmeyer1292** [comment]
@shaun-edwards I'm not attached to my version of SOEM. I'll test this one out with our drivers and report back.

**Comment by shaun-edwards** [comment]
I started a fix [here](https://github.com/shaun-edwards/robotiq/tree/issue39_soem_lib), but I'm blocked until smits/soem#4 is addressed.
