### ISSUE TITLE
Control msg dependency not properly declared

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/robotiq#42]
The `robotiq_action_server` references `control_msgs` in the CMakeLists.txt, but it is not in the package.xml.

This appears to be causing the following [failure](http://jenkins.ros.org/job/devel-indigo-robotiq/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/9/console) on the build farm.

**Comment by shaun-edwards** [comment]
I wonder if `catkin_lint` would have caught this issue?

**Comment by gavanderhoorn** [comment]
yep:

```
robotiq_action_server: error: missing build_depend on 'message_generation'
robotiq_action_server: error: missing build_depend on 'control_msgs'
robotiq_action_server: CMakeLists.txt(34): notice: line is not indented properly
robotiq_action_server: CMakeLists.txt(47): notice: line is not indented properly
robotiq_action_server: CMakeLists.txt(58): notice: line is not indented properly
```

**Comment by gavanderhoorn** [comment]
See also #26.
