### ISSUE TITLE
Release for ROS Jade?

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial-attic/robotiq#52]
Looks like [soem](https://github.com/smits/soem/issues/5) is a missing dependency still, so I just filed an issue there. Is there a plan to soon release this package to Jade?

**Comment by jproberge** [comment]
Soem can be installed from sources, if using a ros version <= Jade . For recent versions >= Kinetic, there is now a debian which can be install using sudo apt-get install ros-[ros_version]-soem.
