### ISSUE TITLE
Run error when loading 2F gripper

### ISSUE THREAD

**Issue by james2254** [ros-industrial-attic/robotiq#55]
when I run "roslaunch robotiq_c_model_control c_model_ethercat.launch" in the terminal,there is a error. what's wrong with it?
![2016-03-29 16 07 27](https://cloud.githubusercontent.com/assets/15374283/14101763/180a4164-f5c9-11e5-9ab8-02c5b23a84f2.png)

**Comment by gavanderhoorn** [comment]
Have you remembered to build your workspace first? And then source the appropriate `setup.bash`?

PS: would you please copy/paste console output like this in the future? Screenshots aren't searchable, and they also make it hard to reply to issues by mail.

**Comment by james2254** [comment]
@gavanderhoorn Thank you help me to point out flaws.I have built my workspace,and run "source devel/setup.bash "in the workspace.

**Comment by gavanderhoorn** [comment]
> I have built my workspace,and run "source devel/setup.bash "in the workspace.

and you still get the same error?.

**Comment by james2254** [comment]
Yes ,my ROS versions is indigo. I have download the soem and install the robotiq-modbus-tcp,then load   the robotiq package from https://github.com/ros-industrial/robotiq .when I  run "roslaunch robotiq_c_model_control c_model_ethercat.launch" in the terminal, still get the same error.

**Comment by gavanderhoorn** [comment]
So you basically do:

``` bash
mkdir /path/to/your/catkin_ws/src
cd /path/to/your/catkin_ws/src

git clone https://github.com/ros-industrial/robotiq.git

cd /path/to/your/catkin_ws

source /opt/ros/indigo/setup.bash
rosdep install --from-paths src --ignore-src

catkin_make

source devel/setup.bash
```

and then finally

``` bash
roslaunch robotiq_c_model_control c_model_ethercat.launch
```

in that same terminal? And that fails with the error message you showed?

[robotiq_c_model_control/CMakeLists.txt](https://github.com/ros-industrial/robotiq/blob/2586c4b4adba3da0ba1c99f5a334296449caaf32/robotiq_c_model_control/CMakeLists.txt#L64-L65) is missing `install(..)` statements for that particular node, so running from an `install` space wouldn't work, but I'd expect a `devel` space to work normally.

After `source devel/setup.bash`, what is the output of `rospack find robotiq_c_model_control`?

**Comment by james2254** [comment]
```
james@james-23-g131cn:~/catkin_ws$ rospack find robotiq_c_model_control
/home/james/catkin_ws/src/robotiq-indigo-devel/robotiq_c_model_control
```

This is the output.

**Comment by gavanderhoorn** [comment]
Ok. And just to make sure: your workspace is basically setup as I described?

Can you tell us what the output is of `ls -al /home/james/catkin_ws/devel/lib/robotiq_c_model_control`?

**Comment by shaun-edwards** [comment]
Thanks @gavanderhoorn for helping out.  @james2254 is this still an issue (it's quite old).  Let me know, otherwise I will close this.

**Comment by james2254** [comment]
I'm sorry for a long time not responding to you. @gavanderhoorn .It works well.You can close it. @shaun-edwards .Thank you very much.
