### ISSUE TITLE
Robotiq FT300 sensor drivers, urdf, models, meshes

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-industrial-attic/robotiq#72]
Do these exist anywhere? Can I use the FT150 driver for the FT300?

**Comment by shaun-edwards** [comment]
@nicolaslauzier (robotiq) is probably the best one to ask.

**Comment by nicolaslauzier** [comment]
The FT300 communicates exactly like the FT150 and as such, the same driver can be used for both sensors. I cannot comment for the urdf, models and meshes as these are from the community (Robotiq provides CAD model, but nothing in a ROS-compatible format).

Hope this helps.

**Comment by UltronDestroyer** [comment]
I've made a PR adding the FT300.

**Comment by felixvd** [comment]
#98
