### ISSUE TITLE
Issue with importing robotiq_cv_model_macro.xacro into my .xacro

### ISSUE THREAD

**Issue by atomoclast** [ros-industrial-attic/robotiq#86]
Hello all, I am trying to make a .xacro file that joins a UR10, a FT150 and a gripper. I am able to attatched and build the urdf as well as use check_urdf to verify the tree. The issue is the second I try to add in the gripper I keep getting this issue:

```
Error:   Failed to find root link: Two root links found: [robotiq_85_adapter_link] and [world]
         at line 238 in /build/buildd/urdfdom-0.2.10+dfsg/urdf_parser/src/model.cpp
ERROR: Model Parsing the xml failed
```

I have no idea what's wrong with the way the file is defined to where it's considering it a world. It looks written properly.

**Comment by gavanderhoorn** [comment]
Could you tell us a bit more (or better yet: show us) how you are combining the three xacro macros into one?

**Comment by shaun-edwards** [comment]
Is this still an issue...can this be closed?

**Comment by shaun-edwards** [comment]
Closing this issue...if this is still an issue, please feel free to comment with more information and we will reopen it.
