### ISSUE TITLE
Kinetic Release?

### ISSUE THREAD

**Issue by SimonBirrell** [ros-industrial-attic/robotiq#89]
Is there an estimated date for a Kinetic release?

Thanks!

Simon

**Comment by shaun-edwards** [comment]
Robotiq is not released as a debian, so there isn't an "official" release.  However, we can't even build the software from source, see #81.  Individuals can overcome these issues, but we'd like to get to solution that works without user modification.

**Comment by jacknlliu** [comment]
I look forward to meeting the kinetic version.

**Comment by mat-l** [comment]
Any updates or progress about the kinetic version yet?
